const ingredients = {
  lasagnaPastaSheets: "lasagna pasta sheets",
  onion: "onion",
  garlic: "garlic",
  oregano: "oregano",
  zucchini: "zucchini",
  mushrooms: "mushrooms",
  himalayaSalt: "himalaya salt",
  blackPepper: "black pepper",
  choppedCannedTomatoes: "chopped canned tomatoes",
  tomato: "tomato",
  tomatoPuree: "tomato puree",
  driedTomatoes: "dried tomatoes",
  nutritionalYeast: "nutritional yeast",
  basil: "basil",
  thyme: "thyme",
  carrot: "carrot",
  redWine: "red wine",
  rosemary: "rosemary",
  cashewNuts: "cashew nuts",
  oatMilk: "oat milk",
  lemonJuice: "lemon juice",
  garlicPowder: "garlic powder",
  onionPowder: "onion powder",
  chickpeas: "chickpeas",
  parsley: "parsley",
  coriander: "coriander",
  bakingPowder: "baking powder",
  salt: "salt",
  cumin: "cumin",
  chilliPepper: "chilli pepper",
  corianderSeeds: "coriander seeds",
  vegetableOil: "vegetable oil",
  flour: "flour",
  yeast: "yeast",
  sugar: "sugar",
  oliveOil: "olive oil",
  water: "water",
  lemon: "lemon",
  bakingSoda: "baking soda",
  tahini: "tahini",
  ginger: "ginger",
  peanutButter: "peanut butter",
  bayLeaves: "bay leaves",
  soyChunks: "soy chunks",
  veganCheeseSpread: "vegan cheese spread",
  berbereSpiceMix: "berbere spice mix",
  greenChiliPeppers: "green chili pepper",
  thaiRedChiliPepper: "Thai red chili pepper",
  cardamom: "cardamom",
  sweetPaprika: "sweet paprika",
  redChiliPepper: "red chili pepper",
  mint: "mint",
  dateSyrup: "date syrop",
}

export default ingredients
