import i from "./ingredients"
const recipesIngredients = {
  "fast-and-special-lasagna": [
    i.lasagnaPastaSheets,
    i.onion,
    i.garlic,
    i.oregano,
    i.zucchini,
    i.mushrooms,
    i.himalayaSalt,
    i.blackPepper,
    i.choppedCannedTomatoes,
    i.tomato,
    i.tomatoPuree,
    i.driedTomatoes,
    i.nutritionalYeast,
    i.basil,
    i.thyme,
    i.carrot,
    i.redWine,
    i.rosemary,
    i.cashewNuts,
    i.oatMilk,
    i.lemonJuice,
    i.garlicPowder,
    i.onionPowder,
  ],
  "home-made-falafel": [
    i.chickpeas,
    i.onion,
    i.garlic,
    i.parsley,
    i.coriander,
    i.bakingPowder,
    i.salt,
    i.cumin,
    i.blackPepper,
    i.chilliPepper,
    i.corianderSeeds,
    i.vegetableOil,
  ],
  "home-made-pita": [i.flour, i.yeast, i.sugar, i.oliveOil, i.salt, i.water],
  "the-ultimate-hummus-protein-bomb": [
    i.chickpeas,
    i.onion,
    i.garlic,
    i.lemon,
    i.cumin,
    i.himalayaSalt,
    i.blackPepper,
    i.bakingSoda,
    i.tahini,
  ],
  "vegan-mafe": [
    i.garlic,
    i.onion,
    i.ginger,
    i.tomatoPuree,
    i.peanutButter,
    i.water,
    i.salt,
    i.cumin,
    i.blackPepper,
    i.bayLeaves,
    i.soyaChunks,
    i.veganCheeseSpread,
    i.berbereSpiceMix,
  ],
}

export default recipesIngredients
