export const BG_COLOR = "whitesmoke"
// export const BG_COLOR = "grey"

export const MAIN_COLOR = "#002940"
export const SECOND_COLOR = "black"
export const GREY = "lightgrey"
export const MAIN_WIDTH = "35rem"
export const ASIDE_WIDTH = "15rem"
export const MAIN_FONT_SIZE = "0.8rem"
export const SMALL_FONT_SIZE = "0.7rem"
export const MAIN_HEADER_SIZE = "1.5rem"
export const MEDIUM_HEADER_SIZE = "1.3rem"
export const SMALL_HEADER_SIZE = "1rem"
